language: php

php:
  - '7.3'
  - '7.4'

install:
  - composer install
  - composer require --dev php-coveralls/php-coveralls

script:
  - mkdir -p build/logs
  - XDEBUG_MODE=coverage phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

